(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'dict' object has no attribute 'ldap_auth'"
p3
sS'layer'
p4
S'/var/www/web2py/applications/teste_ldap/controllers/principal.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n#fun\xc3\xa7\xc3\xa3o de login\ndef login():\n    return auth.login()\n#fun\xc3\xa7\xc3\xa3o index\n@auth.requires_login()\ndef index():\n    return auth.user.first_name\n\ndef logout():\n    return auth.logout()\n\ndef teste():\n    print auth.settings.login_methods[0].func_globals.ldap_auth\n    return auth.settings.login_methods[0].func_globals.ldap_auth\nresponse._vars=response._caller(teste)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 17, in <module>\n  File "/var/www/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 15, in teste\n    print auth.settings.login_methods[0].func_globals.ldap_auth\nAttributeError: \'dict\' object has no attribute \'ldap_auth\'\n'
p11
s.