(dp1
S'output'
p2
S"<type 'exceptions.ImportError'> cannot import name do_manage_groups"
p3
sS'layer'
p4
S'/var/www/web2py/applications/teste_ldap/controllers/principal.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n#fun\xc3\xa7\xc3\xa3o de login\ndef login():\n    return auth.login()\n#fun\xc3\xa7\xc3\xa3o index\n@auth.requires_login()\ndef index():\n    return auth.user.first_name\n\ndef logout():\n    return auth.logout()\n\ndef teste():\n    from gluon.contrib.login_methods.ldap_auth import do_manage_groups\n\n    print do_manage_groups\n    return auth.settings.login_methods[0]\nresponse._vars=response._caller(teste)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 19, in <module>\n  File "/var/www/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 15, in teste\n    from gluon.contrib.login_methods.ldap_auth import do_manage_groups\nImportError: cannot import name do_manage_groups\n'
p11
s.