(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Auth' object has no attribute 'Auth'"
p3
sS'layer'
p4
S'/var/www/web2py/applications/teste_ldap/controllers/principal.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n#fun\xc3\xa7\xc3\xa3o de login\ndef login():\n    form = auth.login()\n    form.element(_name=\'password\')[\'_class\'] = "form-control"\n    form.element(_name=\'password\')[\'_placeholder\'] = \'Senha\'\n    form.element(_type=\'submit\')[\'_class\'] = "btn btn-outline btn-primary btn-lg btn-block"\n    print auth.Auth\n#fun\xc3\xa7\xc3\xa3o index\ndef index():\n    print \'Deu Certo\'\n    return \'Deu Certo\'\nresponse._vars=response._caller(login)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 14, in <module>\n  File "/var/www/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 9, in login\n    print auth.Auth\nAttributeError: \'Auth\' object has no attribute \'Auth\'\n'
p11
s.